FROM annotater/base:0.9


# Install Diamond
RUN wget https://github.com/bbuchfink/diamond/releases/download/v0.9.25/diamond-linux64.tar.gz \
  && tar -zxvf diamond-linux64.tar.gz \
  && mv diamond /usr/local/bin/diamond

